<a href="https://colab.research.google.com/github/mohankishoregorle/numpy/blob/main/mohan_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. Data Manipulation

# Create arrays
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original Array:\n", data)

# Indexing and Slicing
print("Element at position (1,2):", data[1, 2])
print("Slice of array (first 2 rows, all columns):\n", data[:2, :])

# Reshaping
reshaped_data = data.reshape(1, 9)
print("Reshaped Array (1x9):\n", reshaped_data)

# Mathematical Operations
added_data = data + 10
print("Array after adding 10:\n", added_data)

# 2. Data Aggregation

# Summary statistics
mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)
sum_val = np.sum(data)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)
print("Sum:", sum_val)

# 3. Data Analysis using numpy

# Percentiles
percentiles = np.percentile(data, [25, 50, 75])
print("25th, 50th, 75th Percentiles:", percentiles)

# Correlation
corr_matrix = np.corrcoef(data.T)
print("Correlation Matrix:\n", corr_matrix)


Original Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at position (1,2): 60
Slice of array (first 2 rows, all columns):
 [[10 20 30]
 [40 50 60]]
Reshaped Array (1x9):
 [[10 20 30 40 50 60 70 80 90]]
Array after adding 10:
 [[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]
Mean: 50.0
Median: 50.0
Standard Deviation: 25.81988897471611
Sum: 450
25th, 50th, 75th Percentiles: [30. 50. 70.]
Correlation Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**4. Application in Data Science**

**NumPy's Advantages Over Traditional Python Data Structures**

**Performance:** NumPy’s array operations are implemented in C, making them significantly faster than native Python loops or list comprehensions.

**Memory Efficiency:** NumPy arrays consume less memory compared to Python lists, thanks to their fixed-size type.

**Vectorized Operations:** NumPy supports vectorized operations, which allows for efficient computation across entire arrays without explicit loops.

**Real-World Examples**

**Machine Learning:** NumPy is used to handle large datasets, perform matrix operations, and compute various metrics.

**Financial Analysis:** It is used to analyze financial time series data, simulate financial models, and optimize trading strategies.

**Scientific Research:** In research, NumPy handles large datasets from experiments and performs complex mathematical computations required for simulations and data analysis.